"""Baseline: the schema as it stood before the scheduled pipeline.

The 19 tables `bitcap-db` built with `create_all` up to this point — raw,
reference, clean, joins, plus `pipeline_runs` and `gold_snapshots`. Recorded as
a migration so an existing database can be stamped at this revision and upgraded
forward, rather than having to be dropped and rebuilt.

Revision ID: 0001
Revises:
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.sqltypes import Text  # noqa: F401  (used by JSONB variants)

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('custodian_name', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('ticker_verified', sa.Boolean(), nullable=False),
    sa.Column('weight_pct', sa.Float(), nullable=False),
    sa.Column('ai_role', sa.String(), nullable=False),
    sa.Column('holdings_version', sa.Integer(), nullable=False),
    sa.Column('companies_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('isin')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('watermarks', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('definition', sa.String(), nullable=False),
    sa.Column('boundary', sa.String(), nullable=False),
    sa.Column('lab_signal_routable', sa.Boolean(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_labs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_mechanisms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('polarity_note', sa.String(), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_practices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gold_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holding_categories',
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ref_categories.id'], ),
    sa.ForeignKeyConstraint(['isin'], ['holdings.isin'], ),
    sa.PrimaryKeyConstraint('isin', 'category_id')
    )
    op.create_table('holding_lab_exposure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('lab', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('sign', sa.String(), nullable=False),
    sa.Column('magnitude', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('why', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('is_dormant', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['isin'], ['holdings.isin'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin', 'lab', 'kind')
    )
    op.create_table('holding_mechanisms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('mechanism_id', sa.String(), nullable=False),
    sa.Column('sign', sa.String(), nullable=False),
    sa.Column('magnitude', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('why', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['isin'], ['holdings.isin'], ),
    sa.ForeignKeyConstraint(['mechanism_id'], ['ref_mechanisms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin', 'mechanism_id')
    )
    op.create_table('raw_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('first_loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('load_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['load_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('raw_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('load_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['load_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'prompt_version')
    )
    op.create_table('raw_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('usd', sa.Float(), nullable=False),
    sa.Column('seconds', sa.Float(), nullable=False),
    sa.Column('at', sa.String(), nullable=False),
    sa.Column('load_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['load_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'at')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('raw_article_id', sa.Integer(), nullable=False),
    sa.Column('lab', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('published_on', sa.Date(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('text_source', sa.String(), nullable=False),
    sa.Column('feed_category', sa.String(), nullable=True),
    sa.Column('archive_snapshot', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lab'], ['ref_labs.id'], ),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('scoring_version', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('is_signal', sa.Boolean(), nullable=True),
    sa.Column('notable', sa.Boolean(), nullable=False),
    sa.Column('notable_reason', sa.String(), nullable=False),
    sa.Column('dropped_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=False),
    sa.Column('ai_band', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'prompt_version')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('via', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('article_sign', sa.String(), nullable=True),
    sa.Column('article_magnitude', sa.String(), nullable=True),
    sa.Column('article_confidence', sa.String(), nullable=True),
    sa.Column('article_reason', sa.String(), nullable=True),
    sa.Column('article_quote', sa.String(), nullable=True),
    sa.Column('holding_sign', sa.String(), nullable=True),
    sa.Column('holding_magnitude', sa.String(), nullable=True),
    sa.Column('holding_confidence', sa.String(), nullable=True),
    sa.Column('holding_why', sa.String(), nullable=True),
    sa.Column('holding_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['isin'], ['holdings.isin'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'isin', 'route', 'via')
    )
    op.create_table('article_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('sign', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=False),
    sa.Column('quote_repaired', sa.Boolean(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ref_categories.id'], ),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_mechanisms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=False),
    sa.Column('mechanism_id', sa.String(), nullable=False),
    sa.Column('sign', sa.String(), nullable=False),
    sa.Column('magnitude', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=False),
    sa.Column('quote_repaired', sa.Boolean(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
    sa.ForeignKeyConstraint(['mechanism_id'], ['ref_mechanisms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('impact', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=False),
    sa.Column('quote_repaired', sa.Boolean(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['ref_practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_practices')
    op.drop_table('article_mechanisms')
    op.drop_table('article_categories')
    op.drop_table('connections')
    op.drop_table('classifications')
    op.drop_table('articles')
    op.drop_table('raw_costs')
    op.drop_table('raw_classifications')
    op.drop_table('raw_articles')
    op.drop_table('holding_mechanisms')
    op.drop_table('holding_lab_exposure')
    op.drop_table('holding_categories')
    op.drop_table('gold_snapshots')
    op.drop_table('ref_practices')
    op.drop_table('ref_mechanisms')
    op.drop_table('ref_labs')
    op.drop_table('ref_categories')
    op.drop_table('pipeline_runs')
    op.drop_table('holdings')
    # ### end Alembic commands ###
