"""The people register: papers and GitHub become a register of humans.

Papers and GitHub were harvested months ago and nothing ever read them — no
tables, no product surface. This gives them one, deliberately as a register of
*people and their affiliation over time* rather than as a second insight stream:
their value is answering "who works at this lab, and since when", which is what
a departure or a stealth-startup formation is measured against.

`people` is keyed on (lab, source_kind, canonical_name) and resolved through
`person_identity`. Both parts are refusals: a name is not evidence that two
people at different labs are one person, and a GitHub login that matches a paper
byline string is not evidence they are the same human either.

`unresolved_items` is not optional scope. Every harvester already records what
it could not resolve rather than dropping it; a table makes that structural, so
a register's gaps stay visible instead of reading as completeness.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-03 14:33:24.758107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.sqltypes import Text  # noqa: F401  (used by JSONB variants)

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab', sa.String(), nullable=False),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab', 'source_kind', 'canonical_name')
    )
    op.create_table('person_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('ref_url', sa.String(), nullable=False),
    sa.Column('observed_on', sa.Date(), nullable=True),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'source_kind', 'ref_url')
    )
    op.create_table('person_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('lab', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', 'lab')
    )
    op.create_table('raw_github_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('lab', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('first_loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('load_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['load_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org', 'login')
    )
    op.create_table('raw_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('lab', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('first_loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('load_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['load_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('unresolved_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leg', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leg', 'source_id', 'identifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unresolved_items')
    op.drop_table('raw_papers')
    op.drop_table('raw_github_people')
    op.drop_table('person_identity')
    op.drop_table('person_evidence')
    op.drop_table('people')
    # ### end Alembic commands ###
